#!/bin/bash

SCRIPT_URL='https://raw.githubusercontent.com/mai-gh/debiarch/main/pacman'

.updateScript () {
  curl "$SCRIPT_URL" > /usr/bin/pacman &&
  chmod +x /usr/bin/pacman &&
  echo "Successfully updated /usr/bin/pacman from $SCRIPT_URL"
}

### Packager ###
if [[ -n $2 ]]; then
  if [[ $2 = "--noconfirm" ]]; then
    pack=$(echo "$*" | cut -d " " -f3-) # Removes the "--noconfirm" flag from package list
    noCnf="1"
  else
    pack=$(echo "$*" | cut -d " " -f2-) # Keeps whole package list and only cuts the flags
    noCnf="0"
  fi
else
  pack=$2
fi

### Functions ###
.noConfirm () {
  if [[ $noCnf = 1 ]]; then
    echo "-y"
  fi
}

.checkRoot () {
  if [ $EUID != 0 ];then
    echo "error: you cannot perform this operation unless you are root."
    exit
  fi
}

.invalidInput () {
  if [[ -z $1 ]]; then
    echo "error: no operation specified (use -h for help)"
  else
    echo "error: invalid option '$1'"
  fi
}

### Logic ###
case "$1" in
  --update-script) .updateScript; exit;;
  -S)   .checkRoot; apt install "$(.noConfirm)" $pack; exit;;
  -Sy)  .checkRoot; apt update; exit;;
  -Syu) .checkRoot; apt update; apt upgrade; exit;;
  -Ss)  apt search "$pack"; exit;;
  -R)   .checkRoot; apt remove "$(.noConfirm)" $pack; exit;;
  -Ru)  .checkRoot; apt autoremove; exit;;
  -U)   .checkRoot; dpkg -i "$(.noConfirm)" "$pack"; exit;;
  -h|--help) cat /usr/bin/pacman | tail; exit;;
  *) .invalidInput "$@"; exit;;
esac
